# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  # Code formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: detect-private-key

  # Kotlin/Java formatting
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-kotlin
        args: [ --autofix ]

  # Gradle wrapper validation
  - repo: local
    hooks:
      - id: gradle-wrapper-validation
        name: Validate Gradle Wrapper
        entry: gradle/wrapper-validation-action
        language: system
        pass_filenames: false

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]

  # Commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
