name: Dependency Security Check

on:
  # Temporarily disabled due to NVD maintenance (July 24, 2025 until 2:00 PM EDT)
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering only
  # pull_request:
  #   paths:
  #     - '**/build.gradle'
  #     - 'gradle.properties'
  #     - 'gradle.lockfile'
  #     - '**/gradle.lockfile'

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run OWASP dependency check
        run: |
          ./gradlew dependencyCheckAggregate --info

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html
          retention-days: 30

      # Fail the build if high/critical vulnerabilities are found
      - name: Check for vulnerabilities
        run: |
          if grep -q "severity.*High\|severity.*Critical" build/reports/dependency-check-report.html; then
            echo "❌ High or Critical vulnerabilities found!"
            echo "Please review the dependency check report and update vulnerable dependencies."
            exit 1
          else
            echo "✅ No high or critical vulnerabilities found."
          fi

      # Create issue if vulnerabilities found (only on scheduled runs)
      - name: Create security issue
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Alert: Vulnerable Dependencies Detected',
              body: `## Security Alert

              Our automated security scan has detected vulnerable dependencies in the project.

              **Action Required:**
              1. Review the [dependency check report](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              2. Update vulnerable dependencies
              3. Regenerate lock files: \`./gradlew resolveAndLockAll --write-locks\`

              **Priority:** High/Critical vulnerabilities require immediate attention.

              This issue was automatically created by the security scan workflow.`,
              labels: ['security', 'dependencies', 'high-priority']
            })
